//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailTrayNotifier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailTrayNotifier.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture)!;
        public static string NavMail => ResourceManager.GetString("NavMail", resourceCulture)!;
        public static string NavSettings => ResourceManager.GetString("NavSettings", resourceCulture)!;
        public static string AutoStartTitle => ResourceManager.GetString("AutoStartTitle", resourceCulture)!;
        public static string AutoStartDescription => ResourceManager.GetString("AutoStartDescription", resourceCulture)!;
        public static string NotificationTitle => ResourceManager.GetString("NotificationTitle", resourceCulture)!;
        public static string NotificationDescription => ResourceManager.GetString("NotificationDescription", resourceCulture)!;
        public static string AddAccount => ResourceManager.GetString("AddAccount", resourceCulture)!;
        public static string NotificationOffWarning => ResourceManager.GetString("NotificationOffWarning", resourceCulture)!;
        public static string AccountName => ResourceManager.GetString("AccountName", resourceCulture)!;
        public static string Pop3Server => ResourceManager.GetString("Pop3Server", resourceCulture)!;
        public static string SmtpServer => ResourceManager.GetString("SmtpServer", resourceCulture)!;
        public static string UserId => ResourceManager.GetString("UserId", resourceCulture)!;
        public static string Password => ResourceManager.GetString("Password", resourceCulture)!;
        public static string SyncInterval => ResourceManager.GetString("SyncInterval", resourceCulture)!;
        public static string MailWebsite => ResourceManager.GetString("MailWebsite", resourceCulture)!;
        public static string Edit => ResourceManager.GetString("Edit", resourceCulture)!;
        public static string DeleteAccount => ResourceManager.GetString("DeleteAccount", resourceCulture)!;
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture)!;
        public static string Save => ResourceManager.GetString("Save", resourceCulture)!;
        public static string ErrorLabel => ResourceManager.GetString("ErrorLabel", resourceCulture)!;
        public static string AppName => ResourceManager.GetString("AppName", resourceCulture)!;
        public static string TrayStartPolling => ResourceManager.GetString("TrayStartPolling", resourceCulture)!;
        public static string TrayStopPolling => ResourceManager.GetString("TrayStopPolling", resourceCulture)!;
        public static string TraySettings => ResourceManager.GetString("TraySettings", resourceCulture)!;
        public static string TrayExit => ResourceManager.GetString("TrayExit", resourceCulture)!;
        public static string TrayTooltip => ResourceManager.GetString("TrayTooltip", resourceCulture)!;
        public static string TrayTooltipDisabled => ResourceManager.GetString("TrayTooltipDisabled", resourceCulture)!;
        public static string TrayTooltipRunning => ResourceManager.GetString("TrayTooltipRunning", resourceCulture)!;
        public static string TrayTooltipAccountError => ResourceManager.GetString("TrayTooltipAccountError", resourceCulture)!;
        public static string TrayTooltipStopped => ResourceManager.GetString("TrayTooltipStopped", resourceCulture)!;
        public static string TrayTooltipNeedSetup => ResourceManager.GetString("TrayTooltipNeedSetup", resourceCulture)!;
        public static string TrayTooltipError => ResourceManager.GetString("TrayTooltipError", resourceCulture)!;
        public static string AlreadyRunning => ResourceManager.GetString("AlreadyRunning", resourceCulture)!;
        public static string AlertTitle => ResourceManager.GetString("AlertTitle", resourceCulture)!;
        public static string MaxAccountsReached => ResourceManager.GetString("MaxAccountsReached", resourceCulture)!;
        public static string MaxAccountsTitle => ResourceManager.GetString("MaxAccountsTitle", resourceCulture)!;
        public static string DeleteAccountConfirm => ResourceManager.GetString("DeleteAccountConfirm", resourceCulture)!;
        public static string DeleteAccountTitle => ResourceManager.GetString("DeleteAccountTitle", resourceCulture)!;
        public static string AccountNameError => ResourceManager.GetString("AccountNameError", resourceCulture)!;
        public static string InputError => ResourceManager.GetString("InputError", resourceCulture)!;
        public static string MissingFieldsMessage => ResourceManager.GetString("MissingFieldsMessage", resourceCulture)!;
        public static string InvalidMailWebUrl => ResourceManager.GetString("InvalidMailWebUrl", resourceCulture)!;
        public static string ConnectionErrorMessage => ResourceManager.GetString("ConnectionErrorMessage", resourceCulture)!;
        public static string ConnectionErrorTitle => ResourceManager.GetString("ConnectionErrorTitle", resourceCulture)!;
        public static string ResetConfirmMessage => ResourceManager.GetString("ResetConfirmMessage", resourceCulture)!;
        public static string ResetConfirmTitle => ResourceManager.GetString("ResetConfirmTitle", resourceCulture)!;
        public static string ResetCompleted => ResourceManager.GetString("ResetCompleted", resourceCulture)!;
        public static string EnterAccountName => ResourceManager.GetString("EnterAccountName", resourceCulture)!;
        public static string AccountNameTrimmed => ResourceManager.GetString("AccountNameTrimmed", resourceCulture)!;
        public static string AccountNameDuplicate => ResourceManager.GetString("AccountNameDuplicate", resourceCulture)!;
        public static string MinOneAccount => ResourceManager.GetString("MinOneAccount", resourceCulture)!;
        public static string DuplicateAccountName => ResourceManager.GetString("DuplicateAccountName", resourceCulture)!;
        public static string MissingFieldsForAccount => ResourceManager.GetString("MissingFieldsForAccount", resourceCulture)!;
        public static string InvalidMailUrlForAccount => ResourceManager.GetString("InvalidMailUrlForAccount", resourceCulture)!;
        public static string NewAccount => ResourceManager.GetString("NewAccount", resourceCulture)!;
        public static string FieldAccountName => ResourceManager.GetString("FieldAccountName", resourceCulture)!;
        public static string FieldPop3Server => ResourceManager.GetString("FieldPop3Server", resourceCulture)!;
        public static string FieldUserId => ResourceManager.GetString("FieldUserId", resourceCulture)!;
        public static string FieldPassword => ResourceManager.GetString("FieldPassword", resourceCulture)!;
        public static string FieldSyncInterval => ResourceManager.GetString("FieldSyncInterval", resourceCulture)!;
        public static string NewMailSingle => ResourceManager.GetString("NewMailSingle", resourceCulture)!;
        public static string NewMailMultiple => ResourceManager.GetString("NewMailMultiple", resourceCulture)!;
        public static string NewMailLatest => ResourceManager.GetString("NewMailLatest", resourceCulture)!;
        public static string GoToMail => ResourceManager.GetString("GoToMail", resourceCulture)!;
        public static string MailCheckError => ResourceManager.GetString("MailCheckError", resourceCulture)!;
    }
}
